# TODO: Generate this using an Org File?
version: "3.9"

# Docker Reference: https://docs.docker.com/engine/reference/builder/

services:

  sveltekit:
    build:
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - spring
    networks:
      - api-network
    ports:
      - "8080:8080"
    expose: [8080]

  spring:
    build:
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    ports:
      - "8443:8443"
    expose: [8443]
    networks:
      - api-network
      - db-network

  db:
    # Docker Hub Reference: https://hub.docker.com/_/mysql/
    image: mysql
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: passwd
      # MYSQL_DATABASE: swa
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    # TODO: Expose Port if "DEBUG"-Profile is enabled?
    # ports:
    #   - ""
    networks:
      - db-network
    # TODO: How do we enable Caching Sha2-Passwords? Is this enough?
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - db-network
    ports:
      - "8081:8080"
    profiles:
      - test

networks:
  default:
    driver: none
  db-network: {}
  api-network: {}
